id = "itn"
title = "Introduction to Networks"
short = "CCNA 1"
cloth = "teal"
pattern = "rings"

[[chapter]]
number = 1
title = "Networking today"

[[chapter]]
number = 2
title = "Basic switch and end device configuration"

[[chapter]]
number = 3
title = "Protocols and models"

[[chapter]]
number = 4
title = "Physical layer"

[[chapter]]
number = 5
title = "Number systems"

[[chapter]]
number = 6
title = "Data link layer"

[[chapter]]
number = 7
title = "Ethernet switching"

[[chapter]]
number = 8
title = "Network layer"

[[chapter]]
number = 9
title = "Address resolution"

[[chapter]]
number = 10
title = "Basic router configuration"

[[chapter]]
number = 11
title = "IPv4 addressing"

[[chapter]]
number = 12
title = "IPv6 addressing"

[[chapter]]
number = 13
title = "ICMP"

[[chapter]]
number = 14
title = "Transport layer"

[[chapter]]
number = 15
title = "Application layer"

[[chapter]]
number = 16
title = "Network security fundamentals"

[[chapter]]
number = 17
title = "Build a small network"
