[package]
name = "octet"
description = "Octet, a personal CCNA library and lab"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde_json.workspace = true
octet-api = { path = "../../crates/octet-api" }
